"""
Main script for training and sampling POPC lipid diffusion model.
"""

import numpy as np
import torch
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import random
import glob

from lipid_diffusion.data.preprocessor import LipidCoordinatePreprocessor
from lipid_diffusion.data.dataset import LipidDataset
from lipid_diffusion.models.transformer import AtomwiseTransformer
from lipid_diffusion.models.diffusion import DiffusionModel
from lipid_diffusion.training.trainer import train_diffusion_model, generate_samples

def write_pdb(coordinates, filename, chain_id='A', res_name='LIP', res_num=1):
    """
    Write coordinates to a PDB file.

    Args:
        coordinates: (n_atoms, 3) array of coordinates
        filename: Output PDB filename
        chain_id: Chain identifier
        res_name: Residue name (e.g., 'POPC')
        res_num: Residue number
    """
    # POPC atom names - temporary workaround
    atom_names = ['N', 'C12', 'H12A', 'H12B', 'C13', 'H13A', 'H13B', 'H13C', 'C14',
 'H14A', 'H14B', 'H14C', 'C15', 'H15A', 'H15B', 'H15C', 'C11', 'H11A', 'H11B', 'P', 'O13', 'O14', 'O12',
 'O11', 'C1', 'HA', 'HB', 'C2', 'HS', 'O21', 'C21', 'O22', 'C22', 'H2R', 'H2S', 'C3', 'HX', 'HY',
 'O31', 'C31', 'O32', 'C32', 'H2X', 'H2Y', 'C23', 'H3R', 'H3S', 'C24', 'H4R', 'H4S', 'C25', 'H5R', 'H5S',
 'C26', 'H6R', 'H6S', 'C27', 'H7R', 'H7S', 'C28', 'H8R', 'H8S', 'C29', 'H91', 'C210', 'H101', 'C211', 'H11R',
 'H11S', 'C212', 'H12R', 'H12S', 'C213', 'H13R', 'H13S', 'C214', 'H14R', 'H14S', 'C215', 'H15R', 'H15S',
 'C216', 'H16R', 'H16S', 'C217', 'H17R', 'H17S', 'C218', 'H18R', 'H18S', 'H18T', 'C33', 'H3X', 'H3Y', 
 'C34', 'H4X', 'H4Y', 'C35', 'H5X', 'H5Y', 'C36', 'H6X', 'H6Y', 'C37', 'H7X', 'H7Y', 'C38', 'H8X',
 'H8Y', 'C39', 'H9X', 'H9Y', 'C310', 'H10X', 'H10Y', 'C311', 'H11X', 'H11Y', 'C312', 'H12X', 'H12Y',
 'C313', 'H13X', 'H13Y', 'C314', 'H14X', 'H14Y', 'C315', 'H15X', 'H15Y', 'C316', 'H16X', 'H16Y', 'H16Z']
    with open(filename, 'w') as f:
        f.write("REMARK   Generated by POPC Lipid Diffusion Model\n")
        f.write(f"REMARK   {len(coordinates)} atoms\n")

        for i, (coord, atom_name) in enumerate(zip(coordinates, atom_names)):
            # PDB format: ATOM serial name resName chainID resSeq x y z occupancy tempFactor element
            line = (
                f"ATOM  {i+1:5d}  {atom_name:4s}{res_name:3s} {chain_id}{res_num:4d}    "
                f"{coord[0]:8.3f}{coord[1]:8.3f}{coord[2]:8.3f}  1.00  0.00           "
                f"{atom_name[0]:2s}\n"
            )
            f.write(line)

        f.write("END\n")

def main():
    """Example pipeline for training and sampling."""
    
    # 1. Load and preprocess data
    print("Loading coordinate data...")
    preprocessor = LipidCoordinatePreprocessor()
    
    file_paths = sorted(glob.glob('popc/*/*.pdb'))
    random.shuffle(file_paths)
    coords_normalized = preprocessor.process_dataset(file_paths, format='pdb')
    n_atoms = coords_normalized.shape[1]
    
    print(f"Loaded {len(coords_normalized)} conformations with {coords_normalized.shape[1]} atoms each")
    
    # 2. Create dataset and dataloader
    dataset = LipidDataset(coords_normalized)
    dataloader = DataLoader(dataset, batch_size=16, shuffle=True)
    
    # 3. Initialize model
    device = 'mps' if torch.backends.mps.is_available() else 'cpu'
    print(f"Using device: {device}")
    
    model = AtomwiseTransformer(
        n_atoms=n_atoms,
        hidden_dim=128,
        n_heads=4,
        n_layers=3
    )
    
    diffusion = DiffusionModel(
        model=model,
        n_timesteps=1000,
        beta_start=1e-4,
        beta_end=0.02
    )
    
    # Move diffusion schedule to device
    diffusion.to(device)

    # 4. Train
    print("Training model...")
    losses = train_diffusion_model(
        dataloader=dataloader,
        model=model,
        diffusion=diffusion,
        n_epochs=50,
        lr=1e-4,
        device=device
    )
    
    # 5. Generate new samples
    print("Generating new conformations...")
    model.eval()
    new_conformations = generate_samples(
        diffusion=diffusion,
        n_samples=10,
        n_atoms=n_atoms,
        device=device
    )
    
    # Denormalize
    new_conformations_real = preprocessor.denormalize(new_conformations)
    
    print(f"Generated {len(new_conformations_real)} new conformations")
    print(f"Shape: {new_conformations_real.shape}")
    
    # 6. Save results
    # Save each conformation as a separate PDB file
    for i, conf in enumerate(new_conformations_real):
        pdb_filename = f'outputs/generated_conf_{i+1:03d}.pdb'
        write_pdb(conf, pdb_filename, chain_id='A', res_name='POPC')
        print(f"Saved {pdb_filename}")
    
    # Also save as numpy for convenience
    np.save('outputs/generated_conformations.npy', new_conformations_real)
    torch.save(model.state_dict(), 'outputs/diffusion_model.pt')
    
    # 7. Plot training loss
    plt.figure(figsize=(10, 5))
    plt.plot(losses)
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Training Loss')
    plt.savefig('outputs/training_loss.png')
    plt.close()
    
    print("Done! Results saved to 'outputs/' directory")


if __name__ == '__main__':
    main()
